---
- name: Install virtualenv package
  become: yes
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - virtualenv

- name: Create virtualenv directory
  become: yes
  file:
    path: "{{ odoo_venv_path }}"
    state: directory
    mode: 02775
    group: "{{ odoo_default_group }}"

- name: Check if virtualenv is already created
  stat:
    path: "{{ odoo_venv_path }}/bin"
  register: env

- name: Manually create the initial virtualenv
  command: "virtualenv {{ odoo_venv_path }}"
  when: env.stat.isdir is undefined

- name: Change virtualenv permissions
  become: yes
  file:
    path: "{{ odoo_venv_path }}"
    owner: odoo
    group: "{{ odoo_default_group }}"
    mode: 02775
    recurse: yes
